/**
 * Mock Data for Development
 * These will be replaced with real API calls in production
 */

export const mockCategories = [
  {
    id: '1',
    name: 'Smartphones',
    description: 'Latest smartphones and mobile devices',
    slug: 'smartphones',
    image: 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=500',
  },
  {
    id: '2',
    name: 'Laptops',
    description: 'Powerful laptops for work and gaming',
    slug: 'laptops',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
  },
  {
    id: '3',
    name: 'Wearables',
    description: 'Smartwatches, fitness trackers, and more',
    slug: 'wearables',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
  },
  {
    id: '4',
    name: 'Headphones',
    description: 'Premium audio devices',
    slug: 'headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
  },
  {
    id: '5',
    name: 'Cameras',
    description: 'Professional and consumer cameras',
    slug: 'cameras',
    image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500',
  },
  {
    id: '6',
    name: 'Gaming',
    description: 'Gaming consoles and accessories',
    slug: 'gaming',
    image: 'https://images.unsplash.com/photo-1486784460347-c0414ccb34c2?w=500',
  },
]

export const mockBrands = [
  { id: '1', name: 'Apple', logo: 'https://via.placeholder.com/100?text=Apple' },
  { id: '2', name: 'Samsung', logo: 'https://via.placeholder.com/100?text=Samsung' },
  { id: '3', name: 'Sony', logo: 'https://via.placeholder.com/100?text=Sony' },
  { id: '4', name: 'LG', logo: 'https://via.placeholder.com/100?text=LG' },
  { id: '5', name: 'Canon', logo: 'https://via.placeholder.com/100?text=Canon' },
  { id: '6', name: 'Nikon', logo: 'https://via.placeholder.com/100?text=Nikon' },
]

export const mockProducts = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    description: 'Latest iPhone with advanced features',
    price: 1199,
    comparePrice: 1399,
    image: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=500',
    rating: 4.8,
    reviews: 2543,
    category: 'Smartphones',
    brand: 'Apple',
    inStock: true,
  },
  {
    id: '2',
    name: 'MacBook Pro 16"',
    description: 'Powerful laptop for professionals',
    price: 2499,
    comparePrice: 2799,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
    rating: 4.9,
    reviews: 1823,
    category: 'Laptops',
    brand: 'Apple',
    inStock: true,
  },
  {
    id: '3',
    name: 'Samsung Galaxy S24',
    description: 'Premium Android smartphone',
    price: 999,
    comparePrice: 1199,
    image: 'https://images.unsplash.com/photo-1511214126613-db03b3b25e8d?w=500',
    rating: 4.7,
    reviews: 1956,
    category: 'Smartphones',
    brand: 'Samsung',
    inStock: true,
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5',
    description: 'Premium noise-cancelling headphones',
    price: 399,
    comparePrice: 479,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    rating: 4.8,
    reviews: 3421,
    category: 'Headphones',
    brand: 'Sony',
    inStock: true,
  },
  {
    id: '5',
    name: 'iPad Air',
    description: 'Versatile tablet for work and creativity',
    price: 799,
    comparePrice: 899,
    image: 'https://images.unsplash.com/photo-1517932294158-668c29ca6a09?w=500',
    rating: 4.6,
    reviews: 892,
    category: 'Tablets',
    brand: 'Apple',
    inStock: true,
  },
  {
    id: '6',
    name: 'Canon EOS R8',
    description: 'Professional mirrorless camera',
    price: 1499,
    comparePrice: 1799,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500',
    rating: 4.7,
    reviews: 567,
    category: 'Cameras',
    brand: 'Canon',
    inStock: true,
  },
  {
    id: '7',
    name: 'Apple Watch Ultra',
    description: 'Advanced fitness and health tracker',
    price: 799,
    comparePrice: 899,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    rating: 4.8,
    reviews: 1204,
    category: 'Wearables',
    brand: 'Apple',
    inStock: true,
  },
  {
    id: '8',
    name: 'PlayStation 5',
    description: 'Next-gen gaming console',
    price: 499,
    comparePrice: 599,
    image: 'https://images.unsplash.com/photo-1486784460347-c0414ccb34c2?w=500',
    rating: 4.9,
    reviews: 5421,
    category: 'Gaming',
    brand: 'Sony',
    inStock: false,
  },
]

export const mockCoupons = [
  {
    id: '1',
    code: 'WELCOME10',
    description: '10% off on first purchase',
    discount: 10,
    type: 'percentage',
    minAmount: 0,
    expiryDate: '2099-12-31',
  },
  {
    id: '2',
    code: 'SAVE50',
    description: '$50 off on purchases above $500',
    discount: 50,
    type: 'fixed',
    minAmount: 500,
    expiryDate: '2099-12-31',
  },
  {
    id: '3',
    code: 'SUMMER20',
    description: '20% off summer sale',
    discount: 20,
    type: 'percentage',
    minAmount: 0,
    expiryDate: '2099-12-31',
  },
]

export const mockFAQs = [
  {
    id: '1',
    question: 'What is your return policy?',
    answer:
      'We offer a 30-day money-back guarantee on all products. If you are not satisfied with your purchase, you can return it for a full refund.',
  },
  {
    id: '2',
    question: 'How long does shipping take?',
    answer:
      'We offer standard shipping (5-7 business days) and express shipping (1-2 business days). Shipping times are calculated from the order date.',
  },
  {
    id: '3',
    question: 'Do you offer warranty on products?',
    answer:
      'Yes, all our products come with manufacturer warranties. We also offer extended warranty options at checkout.',
  },
  {
    id: '4',
    question: 'Can I track my order?',
    answer:
      'Yes, once your order is shipped, you will receive a tracking number via email. You can use this to track your package in real-time.',
  },
  {
    id: '5',
    question: 'Is it safe to shop on your site?',
    answer:
      'Yes, we use industry-standard SSL encryption to protect your personal and payment information. Your security is our top priority.',
  },
]

export const mockReviews = [
  {
    id: '1',
    productId: '1',
    author: 'John Doe',
    rating: 5,
    title: 'Excellent phone, highly recommended!',
    content: 'The iPhone 15 Pro Max is amazing. Great camera, fast processor, and beautiful display. Very satisfied with my purchase.',
    date: '2 weeks ago',
    verified: true,
  },
  {
    id: '2',
    productId: '1',
    author: 'Jane Smith',
    rating: 4,
    title: 'Very good, but a bit pricey',
    content: 'Great phone overall. The camera is fantastic and the performance is smooth. The price is on the higher side though.',
    date: '1 month ago',
    verified: true,
  },
  {
    id: '3',
    productId: '2',
    author: 'Alex Johnson',
    rating: 5,
    title: 'Perfect for professional work',
    content: 'The MacBook Pro is incredible. Fast, reliable, and the build quality is exceptional. Best laptop I\'ve ever owned.',
    date: '1 week ago',
    verified: true,
  },
  {
    id: '4',
    productId: '2',
    author: 'Mike Wilson',
    rating: 5,
    title: 'Worth every penny',
    content: 'Excellent machine for video editing and 3D work. Performance is outstanding and never slows down.',
    date: '3 weeks ago',
    verified: true,
  },
  {
    id: '5',
    productId: '4',
    author: 'Sarah Chen',
    rating: 5,
    title: 'Best headphones ever',
    content: 'The Sony WH-1000XM5 has the best noise cancellation I\'ve ever experienced. Sound quality is amazing.',
    date: '1 week ago',
    verified: true,
  },
  {
    id: '6',
    productId: '4',
    author: 'Tom Brown',
    rating: 4,
    title: 'Great sound, bit heavy',
    content: 'Excellent audio quality and noise cancellation. A bit heavy on the head after long hours but still very good.',
    date: '2 weeks ago',
    verified: true,
  },
]
